# -*- coding: utf-8 -*-
"""Condicional

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtB-ueD8vnv-jjdbLu8aDN9zkyvXdUlP
"""

a=3
b=2
if a > b:
  print("A es mayor que B")
else:
  print("B es mayor que A")

"""En este codigo cree un condicional sencillo para determinar cual es el mayor numero entre dos opciones."""